usethis::use_build_ignore("devtools_history.R")
usethis::use_package("stats")
usethis::use_package("glmnet")
usethis::use_package("gtools")
usethis::use_package("gfpop")
usethis::use_package("bazar")
